export const COLORS = {
    'black': '#000000',
    'darkblue': '#000080',
    'darkgreen': '#008000',
    'darkcyan': '#008080',
    'darkred': '#800000',
    'darkmagenta': '#800080',
    'olive': '#808000',
    'darkgray': '#808080',
    'blue': '#0000FF',
    'green': '#00FF00',
    'cyan': '#00FFFF',
    'red': '#FF0000',
    'magenta': '#FF00FF',
    'yellow': '#FFFF00',
    'gray': '#C0C0C0',
    'white': '#FFFFFF',
};

export const initialTableData = [
    [['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X']],
    [['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X']],
    [['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X']],
    [['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X']],
    [['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X']],
    [['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X']],
    [['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X']],
    [['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X']],
    [['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X']],
    [['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X'], ['#ffffff', 'X']],
];
